# Demo environment configuration 

- name: Configure CDN Demo application on F5 Distributed Cloud 
  hosts: webservers
  collections:
    - f5_xc_cloud.xc_cloud_modules
  connection: local

  environment:
      XC_API_TOKEN: "your_api_token"
      XC_TENANT: "your_tenant_name.console.ves.volterra.io"

  vars:
      xc_namespace: "cdn-demo-guide"
      prefix: ""
      domain: "your_domain.example.com"
      dns_volterra_managed: False
      buytime_online: "54.208.44.177"

  tasks:
    - name: Fetch current tenant details
      tenant_settings_info:
      register: tenant_settings

    - name: Create namespace
      namespace:
        wait_for_completion: True
        state: present
        metadata:
          name: "{{ xc_namespace }}"
          description: "Namespace for Ansible demo"

    - name: Health check
      health_check:
        state: present
        metadata:
          namespace: "{{ xc_namespace }}"
          name: "{{ prefix }}buytime-hc"
        spec:
          http_health_check:
            path: "/"
            expected_status_codes:
              - "200"
              - "204"
            headers:
              "User-Agent": "F5-XC-HealthCheck"
            use_http2: False
          interval: 30
          timeout: 10
          healthy_threshold: 2
          unhealthy_threshold: 3
          jitter_percent: 10

    - name: Create origin pool
      origin_pool:
        state: present
        metadata:
          namespace: "{{ xc_namespace }}"
          name: "{{ prefix }}buytime-pool"
        spec:
          origin_servers:
            - public_ip:
                ip: "{{ buytime_online }}"
          port: 80
          loadbalancer_algorithm: "LB_OVERRIDE"
          endpoint_selection: "LOCAL_PREFERRED"
          healthcheck:
            - tenant: "{{ tenant_settings.tenant.name }}"
              namespace: "{{ xc_namespace }}"
              name: "{{ prefix }}buytime-hc"

    - name: Create app firewall
      application_firewall:
        state: present
        metadata:
          namespace: "{{ xc_namespace }}"
          name: "{{ prefix }}buytime-fw"
        spec:
          blocking: {}
          detection_settings:
            signature_selection_setting:
              attack_type_settings:
                disabled_attack_types:
                  - "ATTACK_TYPE_COMMAND_EXECUTION"
              high_medium_low_accuracy_signatures: {}
            enable_suppression: { }
            enable_threat_campaigns: { }
            violation_settings:
              disabled_violation_types:
                - "VIOL_HTTP_PROTOCOL_BAD_HTTP_VERSION"
            bot_protection_setting:
              good_bot_action: "REPORT"
              malicious_bot_action: "BLOCK"
              suspicious_bot_action: "REPORT"
          allow_all_response_codes: {}
          default_anonymization: {}
          blocking_page:
            response_code: "Forbidden"
            blocking_page: "string:///PGh0bWw+PGhlYWQ+PHRpdGxlPlJlcXVlc3QgUmVqZWN0ZWQ8L3RpdGxlPjwvaGVhZD48Ym9keT5UaGUgcmVxdWVzdGVkIFVSTCB3YXMgcmVqZWN0ZWQuIFBsZWFzZSBjb25zdWx0IHdpdGggeW91ciBhZG1pbmlzdHJhdG9yLjxici8+PGJyLz5Zb3VyIHN1cHBvcnQgSUQgaXM6IHt7cmVxdWVzdF9pZH19PGJyLz48YnIvPjxhIGhyZWY9ImphdmFzY3JpcHQ6aGlzdG9yeS5iYWNrKCkiPltHbyBCYWNrXTwvYT48L2JvZHk+PC9odG1sPg=="

    - name: Create load balancer
      http_loadbalancer:
        state: present
        metadata:
          namespace: "{{ xc_namespace }}"
          name: "{{ prefix }}buytime-https-lb"
        spec:
          domains:
            - "waap.{{ domain }}"
          https_auto_cert:
            http_redirect: True
            add_hsts: True
            port: 443
            tls_config:
              default_security: {}
            no_mtls: {}
            default_header: {}
            enable_path_normalize: {}
            non_default_loadbalancer: {}
          default_route_pools:
            - pool:
                tenant: "{{ tenant_settings.tenant.name }}"
                namespace: "{{ xc_namespace }}"
                name: "{{ prefix }}buytime-pool"
              weight: 1
              priority: 1
          app_firewall:
            tenant: "{{ tenant_settings.tenant.name }}"
            namespace: "{{ xc_namespace }}"
            name: "{{ prefix }}buytime-fw"

    - name: Fetch load balancer
      http_loadbalancer_info:
        namespace: "{{ xc_namespace }}"
        name: "{{ prefix }}buytime-https-lb"
      register: waap_lb
      retries: 10
      delay: 10 
      until: >
        waap_lb.resources[0].spec.host_name != "" and
        waap_lb.resources[0].spec.auto_cert_info.dns_records is defined and
        waap_lb.resources[0].spec.auto_cert_info.dns_records[0].name != ""
      when: dns_volterra_managed == False

    - name: Create CDN distribution
      cdn_loadbalancer:
        state: present
        metadata:
          namespace: "{{ xc_namespace }}"
          name: "{{ prefix }}buytime-https-cdn-distribution"
        spec:
          domains:
            - "cdn.{{ domain }}"
          https_auto_cert:
            http_redirect: True
            add_hsts: True
            tls_config:
              tls_12_plus: {}
          origin_pool:
            public_name:
              dns_name: "waap.{{ domain }}"
              refresh_interval: 300
            use_tls:
              use_host_header_as_sni: {}
              tls_config:
                default_security: {}
              volterra_trusted_ca: {}
              no_mtls: {}
              default_session_key_caching: {}
            origin_servers:
              - public_name:
                  dns_name: "waap.{{ domain }}"
                port: 443
          default_cache_action:
            cache_ttl_override: "1d"
          # app_firewall:
          #   tenant: "{{ tenant_settings.tenant.name }}"
          #   namespace: "{{ xc_namespace }}"
          #   name: "{{ prefix }}buytime-fw"

    - name: Fetch CDN load balancer
      cdn_loadbalancer_info:
        namespace: "{{ xc_namespace }}"
        name: "{{ prefix }}buytime-https-cdn-distribution"
      register: cdn_lb
      retries: 10
      delay: 10
      until: >
              cdn_lb.resources[0].spec.service_domains[0].service_domain != "" and
              cdn_lb.resources[0].spec.auto_cert_info.dns_records is defined and
              cdn_lb.resources[0].spec.auto_cert_info.dns_records[0].name != ""
      when: dns_volterra_managed == False

    - name: debug info
      debug:
        var: waap_lb

    - name: WAAP DNS Records
      debug:
        msg:
          - "-------- WAAP CNAME RECORDS --------"
          - "Record: {{ waap_lb.resources[0].spec.domains[0] }}"
          - "Value: {{ waap_lb.resources[0].spec.host_name }}"
          - "-----------------------------------"
          - "Record: {{ waap_lb.resources[0].spec.auto_cert_info.dns_records[0].name }}"
          - "Value: {{ waap_lb.resources[0].spec.auto_cert_info.dns_records[0].value }}"
          - "-----------------------------------"
      when: dns_volterra_managed == False

    - name: CDN DNS Records
      debug:
        msg:
          - "-------- CDN CNAME RECORDS --------"
          - "Record: {{ cdn_lb.resources[0].spec.service_domains[0].domain }}"
          - "Value: {{ cdn_lb.resources[0].spec.service_domains[0].service_domain }}"
          - "----------------------------------"
          - "Record: {{ cdn_lb.resources[0].spec.auto_cert_info.dns_records[0].name }}"
          - "Value: {{ cdn_lb.resources[0].spec.auto_cert_info.dns_records[0].value }}"
          - "----------------------------------"
      when: dns_volterra_managed == False

    - name: Endpoints
      debug:
       msg:
        - "WAAP: https://waap.{{ domain }}"
        - "CDN: https://cdn.{{ domain }}"
